stunning/restaurants/urls.py
from django.conf.urls import url

from .views import (RestaurantCreation, RestaurantDelete, RestaurantDetail,
                    RestaurantList, RestaurantUpdate)

urlpatterns = [
    url(r'^$', RestaurantList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', RestaurantDetail.as_view(), name='detail'),
    url(r'^new$', RestaurantCreation.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', RestaurantUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', RestaurantDelete.as_view(), name='delete'),

]

stunning/stunning/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
]

stunning/restaurants/models.py
# -*- encoding: utf-8 -*-
from django.db import models


class Restaurant(models.Model):
    """Structure of the object Restaurant."""
    name = models.CharField("Nombre", max_length=140, unique=True)
    rating = models.IntegerField("Valoración", default=0)
    phone = models.CharField("Teléfono", max_length=15)
    city = models.CharField("Ciudad", max_length=150)

    def __unicode__(self):
        return self.name

stunning/restaurants/views.py
# from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Restaurant


class RestaurantList(ListView):
    model = Restaurant


class RestaurantDetail(DetailView):
    model = Restaurant


class RestaurantCreation(CreateView):
    model = Restaurant
    success_url = reverse_lazy('restaurants:list')
    fields = ['name', 'rating', 'phone', 'city']


class RestaurantUpdate(UpdateView):
    model = Restaurant
    success_url = reverse_lazy('restaurants:list')
    fields = ['name', 'rating', 'phone', 'city']


class RestaurantDelete(DeleteView):
    model = Restaurant
    success_url = reverse_lazy('restaurants:list')

stunning/restaurants/templates/restaurants/restaurant_confirm_delete.html
<form method="post">{% csrf_token %}
    ¿Estás seguro que deseas borrar el restaurante "{{ object }}"?
    <input type="submit" value="Aceptar" />
</form>

stunning/restaurants/templates/restaurants/restaurant_detail.html
{% load static from staticfiles  %}
<h1>{{ restaurant.name }}</h1>
<p>Valorado <i>{{ restaurant.rating }}</i></p>
<p>Telefono <i>{{ restaurant.phone }}</i></p>
<p>Ciudad <i>{{ restaurant.city }}</i></p>
<p>
    <a href="{% url "restaurants:list" %}">Regresar</a>
</p>

stunning/restaurants/templates/restaurants/restaurant_form.html
<form class=""   enctype="multipart/form-data" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="" value="Guardar">
</form>

stunning/restaurants/templates/restaurants/restaurant_list.html
<h1>Restaurantes de México</h1>

<p>
    <a href="{% url "restaurants:new" %}">Agregar restaurante</a>
</p>

<ul>
    {% for restaurant in object_list %}
        <li>
            <p>{{ restaurant.name }}</p>
            <p>
                <a href="{% url "restaurants:detail" restaurant.id %}">Ver</a> | 
                <a href="{% url "restaurants:edit" restaurant.id %}">Editar</a> |
                <a href="{% url "restaurants:delete" restaurant.id %}">Borrar</a>
            </p>
        </li>
    {% endfor %}
</ul>